version: "3.8"

services:
  web:
    build:
      context: ./apps/web
    ports:
      - "5000:5000"
    volumes:
      - .:/code
    environment:
      FLASK_ENV: development

  server:
    build:
      context: ./apps/backend
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    environment:
      DJANGO_ENV: development

  site:
    build:
      context: ./apps/frontend
    ports:
      - "3000:3000"
    volumes:
      - .:/code
    environment:
      REACT_ENV: development
