/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
	export interface Resource {
		AwsAccessKeyId: {
			type: "sst.sst.Secret"
			value: string
		}
		AwsSecretAccessKey: {
			type: "sst.sst.Secret"
			value: string
		}
		CodelabsBucket: {
			name: string
			type: "sst.aws.Bucket"
		}
		CodelabsDatabase: {
			database: string
			host: string
			password: string
			port: number
			type: "sst.aws.Postgres"
			username: string
		}
		CodelabsRealtimeServer: {
			service: string
			type: "sst.aws.Service"
			url: string
		}
		CodelabsRedis: {
			host: string
			password: string
			port: number
			type: "sst.aws.Redis"
			username: string
		}
		CodelabsVPC: {
			type: "sst.aws.Vpc"
		}
		CodelabsWeb: {
			type: "sst.aws.SvelteKit"
			url: string
		}
		ResendApiKey: {
			type: "sst.sst.Secret"
			value: string
		}
	}
}
/// <reference path="sst-env.d.ts" />

import "sst"
